"""Alternative method for searching the graph of safe sets in the ISS

The safe-set of boxes in the ISS is pretty small, so it's not too hard to just enumerate all of the paths between 
different boxes and use a lookup table. 

PATHS[start][end] will yield a list of safe boxes from start to end

As compared with depth-first-search, the lookup table is about 10x faster using timeit

To recompute the lookup table, re-run the script, copy the output here, and autoformat the file with Black
"""

from collections import defaultdict

from pyastrobee.config.iss_safe_boxes import ISSBox, compute_iss_graph
from pyastrobee.utils.algos import dfs


# Slightly hacky but it works
def _dp_dfs(graph) -> dict[ISSBox, dict[ISSBox, list[ISSBox]]]:
    dp = defaultdict(dict)
    for start in graph:
        for end in graph:
            if start in dp and end in dp[start]:
                continue
            else:
                path = dfs(graph, start, end)
                for i in range(len(path)):
                    for j in range(i, len(path)):
                        dp[path[i]][path[j]] = path[i : j + 1]
    return dp


def create_path_lookup_table():
    m = compute_iss_graph()
    all_paths = _dp_dfs(m)
    print("{")
    for start in all_paths:
        print(start, ": {")
        for end in all_paths:
            path = all_paths[start][end]
            print(end, ": [", end="")
            for i, loc in enumerate(path):
                print(loc, end="")
                if i != len(path) - 1:
                    print(", ", end="")
            print("],")
        print("},")
    print("}")


PATHS = {
    ISSBox.JPM: {
        ISSBox.JPM: [ISSBox.JPM],
        ISSBox.JPM_N2_CORRIDOR: [ISSBox.JPM, ISSBox.JPM_N2_CORRIDOR],
        ISSBox.NODE_2: [ISSBox.JPM, ISSBox.JPM_N2_CORRIDOR, ISSBox.NODE_2],
        ISSBox.N2_EU_CORRIDOR: [
            ISSBox.JPM,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
        ],
        ISSBox.N2_US_CORRIDOR: [
            ISSBox.JPM,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
        ],
        ISSBox.EU_LAB: [
            ISSBox.JPM,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.EU_LAB,
        ],
        ISSBox.US_LAB: [
            ISSBox.JPM,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
        ],
        ISSBox.US_N1_CORRIDOR: [
            ISSBox.JPM,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
        ],
        ISSBox.NODE_1: [
            ISSBox.JPM,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
        ],
        ISSBox.N1_N3_CORRIDOR: [
            ISSBox.JPM,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
        ],
        ISSBox.NODE_3_A: [
            ISSBox.JPM,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
        ],
        ISSBox.NODE_3_B: [
            ISSBox.JPM,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
        ],
        ISSBox.N3_CUPOLA_CORRIDOR: [
            ISSBox.JPM,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
        ],
        ISSBox.CUPOLA: [
            ISSBox.JPM,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.CUPOLA,
        ],
    },
    ISSBox.JPM_N2_CORRIDOR: {
        ISSBox.JPM: [ISSBox.JPM_N2_CORRIDOR, ISSBox.JPM],
        ISSBox.JPM_N2_CORRIDOR: [ISSBox.JPM_N2_CORRIDOR],
        ISSBox.NODE_2: [ISSBox.JPM_N2_CORRIDOR, ISSBox.NODE_2],
        ISSBox.N2_EU_CORRIDOR: [
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
        ],
        ISSBox.N2_US_CORRIDOR: [
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
        ],
        ISSBox.EU_LAB: [
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.EU_LAB,
        ],
        ISSBox.US_LAB: [
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
        ],
        ISSBox.US_N1_CORRIDOR: [
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
        ],
        ISSBox.NODE_1: [
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
        ],
        ISSBox.N1_N3_CORRIDOR: [
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
        ],
        ISSBox.NODE_3_A: [
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
        ],
        ISSBox.NODE_3_B: [
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
        ],
        ISSBox.N3_CUPOLA_CORRIDOR: [
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
        ],
        ISSBox.CUPOLA: [
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.CUPOLA,
        ],
    },
    ISSBox.NODE_2: {
        ISSBox.JPM: [ISSBox.NODE_2, ISSBox.JPM_N2_CORRIDOR, ISSBox.JPM],
        ISSBox.JPM_N2_CORRIDOR: [ISSBox.NODE_2, ISSBox.JPM_N2_CORRIDOR],
        ISSBox.NODE_2: [ISSBox.NODE_2],
        ISSBox.N2_EU_CORRIDOR: [ISSBox.NODE_2, ISSBox.N2_EU_CORRIDOR],
        ISSBox.N2_US_CORRIDOR: [ISSBox.NODE_2, ISSBox.N2_US_CORRIDOR],
        ISSBox.EU_LAB: [ISSBox.NODE_2, ISSBox.N2_EU_CORRIDOR, ISSBox.EU_LAB],
        ISSBox.US_LAB: [ISSBox.NODE_2, ISSBox.N2_US_CORRIDOR, ISSBox.US_LAB],
        ISSBox.US_N1_CORRIDOR: [
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
        ],
        ISSBox.NODE_1: [
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
        ],
        ISSBox.N1_N3_CORRIDOR: [
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
        ],
        ISSBox.NODE_3_A: [
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
        ],
        ISSBox.NODE_3_B: [
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
        ],
        ISSBox.N3_CUPOLA_CORRIDOR: [
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
        ],
        ISSBox.CUPOLA: [
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.CUPOLA,
        ],
    },
    ISSBox.N2_EU_CORRIDOR: {
        ISSBox.JPM: [
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.JPM,
        ],
        ISSBox.JPM_N2_CORRIDOR: [
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
        ],
        ISSBox.NODE_2: [ISSBox.N2_EU_CORRIDOR, ISSBox.NODE_2],
        ISSBox.N2_EU_CORRIDOR: [ISSBox.N2_EU_CORRIDOR],
        ISSBox.N2_US_CORRIDOR: [
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
        ],
        ISSBox.EU_LAB: [ISSBox.N2_EU_CORRIDOR, ISSBox.EU_LAB],
        ISSBox.US_LAB: [
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
        ],
        ISSBox.US_N1_CORRIDOR: [
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
        ],
        ISSBox.NODE_1: [
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
        ],
        ISSBox.N1_N3_CORRIDOR: [
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
        ],
        ISSBox.NODE_3_A: [
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
        ],
        ISSBox.NODE_3_B: [
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
        ],
        ISSBox.N3_CUPOLA_CORRIDOR: [
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
        ],
        ISSBox.CUPOLA: [
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.CUPOLA,
        ],
    },
    ISSBox.N2_US_CORRIDOR: {
        ISSBox.JPM: [
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.JPM,
        ],
        ISSBox.JPM_N2_CORRIDOR: [
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
        ],
        ISSBox.NODE_2: [ISSBox.N2_US_CORRIDOR, ISSBox.NODE_2],
        ISSBox.N2_EU_CORRIDOR: [
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
        ],
        ISSBox.N2_US_CORRIDOR: [ISSBox.N2_US_CORRIDOR],
        ISSBox.EU_LAB: [
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.EU_LAB,
        ],
        ISSBox.US_LAB: [ISSBox.N2_US_CORRIDOR, ISSBox.US_LAB],
        ISSBox.US_N1_CORRIDOR: [
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
        ],
        ISSBox.NODE_1: [
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
        ],
        ISSBox.N1_N3_CORRIDOR: [
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
        ],
        ISSBox.NODE_3_A: [
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
        ],
        ISSBox.NODE_3_B: [
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
        ],
        ISSBox.N3_CUPOLA_CORRIDOR: [
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
        ],
        ISSBox.CUPOLA: [
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.CUPOLA,
        ],
    },
    ISSBox.EU_LAB: {
        ISSBox.JPM: [
            ISSBox.EU_LAB,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.JPM,
        ],
        ISSBox.JPM_N2_CORRIDOR: [
            ISSBox.EU_LAB,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
        ],
        ISSBox.NODE_2: [ISSBox.EU_LAB, ISSBox.N2_EU_CORRIDOR, ISSBox.NODE_2],
        ISSBox.N2_EU_CORRIDOR: [ISSBox.EU_LAB, ISSBox.N2_EU_CORRIDOR],
        ISSBox.N2_US_CORRIDOR: [
            ISSBox.EU_LAB,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
        ],
        ISSBox.EU_LAB: [ISSBox.EU_LAB],
        ISSBox.US_LAB: [
            ISSBox.EU_LAB,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
        ],
        ISSBox.US_N1_CORRIDOR: [
            ISSBox.EU_LAB,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
        ],
        ISSBox.NODE_1: [
            ISSBox.EU_LAB,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
        ],
        ISSBox.N1_N3_CORRIDOR: [
            ISSBox.EU_LAB,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
        ],
        ISSBox.NODE_3_A: [
            ISSBox.EU_LAB,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
        ],
        ISSBox.NODE_3_B: [
            ISSBox.EU_LAB,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
        ],
        ISSBox.N3_CUPOLA_CORRIDOR: [
            ISSBox.EU_LAB,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
        ],
        ISSBox.CUPOLA: [
            ISSBox.EU_LAB,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.CUPOLA,
        ],
    },
    ISSBox.US_LAB: {
        ISSBox.JPM: [
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.JPM,
        ],
        ISSBox.JPM_N2_CORRIDOR: [
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
        ],
        ISSBox.NODE_2: [ISSBox.US_LAB, ISSBox.N2_US_CORRIDOR, ISSBox.NODE_2],
        ISSBox.N2_EU_CORRIDOR: [
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
        ],
        ISSBox.N2_US_CORRIDOR: [ISSBox.US_LAB, ISSBox.N2_US_CORRIDOR],
        ISSBox.EU_LAB: [
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.EU_LAB,
        ],
        ISSBox.US_LAB: [ISSBox.US_LAB],
        ISSBox.US_N1_CORRIDOR: [ISSBox.US_LAB, ISSBox.US_N1_CORRIDOR],
        ISSBox.NODE_1: [ISSBox.US_LAB, ISSBox.US_N1_CORRIDOR, ISSBox.NODE_1],
        ISSBox.N1_N3_CORRIDOR: [
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
        ],
        ISSBox.NODE_3_A: [
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
        ],
        ISSBox.NODE_3_B: [
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
        ],
        ISSBox.N3_CUPOLA_CORRIDOR: [
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
        ],
        ISSBox.CUPOLA: [
            ISSBox.US_LAB,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.CUPOLA,
        ],
    },
    ISSBox.US_N1_CORRIDOR: {
        ISSBox.JPM: [
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.JPM,
        ],
        ISSBox.JPM_N2_CORRIDOR: [
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
        ],
        ISSBox.NODE_2: [
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
        ],
        ISSBox.N2_EU_CORRIDOR: [
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
        ],
        ISSBox.N2_US_CORRIDOR: [
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
        ],
        ISSBox.EU_LAB: [
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.EU_LAB,
        ],
        ISSBox.US_LAB: [ISSBox.US_N1_CORRIDOR, ISSBox.US_LAB],
        ISSBox.US_N1_CORRIDOR: [ISSBox.US_N1_CORRIDOR],
        ISSBox.NODE_1: [ISSBox.US_N1_CORRIDOR, ISSBox.NODE_1],
        ISSBox.N1_N3_CORRIDOR: [
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
        ],
        ISSBox.NODE_3_A: [
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
        ],
        ISSBox.NODE_3_B: [
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
        ],
        ISSBox.N3_CUPOLA_CORRIDOR: [
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
        ],
        ISSBox.CUPOLA: [
            ISSBox.US_N1_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.CUPOLA,
        ],
    },
    ISSBox.NODE_1: {
        ISSBox.JPM: [
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.JPM,
        ],
        ISSBox.JPM_N2_CORRIDOR: [
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
        ],
        ISSBox.NODE_2: [
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
        ],
        ISSBox.N2_EU_CORRIDOR: [
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
        ],
        ISSBox.N2_US_CORRIDOR: [
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
        ],
        ISSBox.EU_LAB: [
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.EU_LAB,
        ],
        ISSBox.US_LAB: [ISSBox.NODE_1, ISSBox.US_N1_CORRIDOR, ISSBox.US_LAB],
        ISSBox.US_N1_CORRIDOR: [ISSBox.NODE_1, ISSBox.US_N1_CORRIDOR],
        ISSBox.NODE_1: [ISSBox.NODE_1],
        ISSBox.N1_N3_CORRIDOR: [ISSBox.NODE_1, ISSBox.N1_N3_CORRIDOR],
        ISSBox.NODE_3_A: [ISSBox.NODE_1, ISSBox.N1_N3_CORRIDOR, ISSBox.NODE_3_A],
        ISSBox.NODE_3_B: [
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
        ],
        ISSBox.N3_CUPOLA_CORRIDOR: [
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
        ],
        ISSBox.CUPOLA: [
            ISSBox.NODE_1,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.CUPOLA,
        ],
    },
    ISSBox.N1_N3_CORRIDOR: {
        ISSBox.JPM: [
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.JPM,
        ],
        ISSBox.JPM_N2_CORRIDOR: [
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
        ],
        ISSBox.NODE_2: [
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
        ],
        ISSBox.N2_EU_CORRIDOR: [
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
        ],
        ISSBox.N2_US_CORRIDOR: [
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
        ],
        ISSBox.EU_LAB: [
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.EU_LAB,
        ],
        ISSBox.US_LAB: [
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
        ],
        ISSBox.US_N1_CORRIDOR: [
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
        ],
        ISSBox.NODE_1: [ISSBox.N1_N3_CORRIDOR, ISSBox.NODE_1],
        ISSBox.N1_N3_CORRIDOR: [ISSBox.N1_N3_CORRIDOR],
        ISSBox.NODE_3_A: [ISSBox.N1_N3_CORRIDOR, ISSBox.NODE_3_A],
        ISSBox.NODE_3_B: [ISSBox.N1_N3_CORRIDOR, ISSBox.NODE_3_A, ISSBox.NODE_3_B],
        ISSBox.N3_CUPOLA_CORRIDOR: [
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
        ],
        ISSBox.CUPOLA: [
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.CUPOLA,
        ],
    },
    ISSBox.NODE_3_A: {
        ISSBox.JPM: [
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.JPM,
        ],
        ISSBox.JPM_N2_CORRIDOR: [
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
        ],
        ISSBox.NODE_2: [
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
        ],
        ISSBox.N2_EU_CORRIDOR: [
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
        ],
        ISSBox.N2_US_CORRIDOR: [
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
        ],
        ISSBox.EU_LAB: [
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.EU_LAB,
        ],
        ISSBox.US_LAB: [
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
        ],
        ISSBox.US_N1_CORRIDOR: [
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
        ],
        ISSBox.NODE_1: [ISSBox.NODE_3_A, ISSBox.N1_N3_CORRIDOR, ISSBox.NODE_1],
        ISSBox.N1_N3_CORRIDOR: [ISSBox.NODE_3_A, ISSBox.N1_N3_CORRIDOR],
        ISSBox.NODE_3_A: [ISSBox.NODE_3_A],
        ISSBox.NODE_3_B: [ISSBox.NODE_3_A, ISSBox.NODE_3_B],
        ISSBox.N3_CUPOLA_CORRIDOR: [
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
        ],
        ISSBox.CUPOLA: [
            ISSBox.NODE_3_A,
            ISSBox.NODE_3_B,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.CUPOLA,
        ],
    },
    ISSBox.NODE_3_B: {
        ISSBox.JPM: [
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.JPM,
        ],
        ISSBox.JPM_N2_CORRIDOR: [
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
        ],
        ISSBox.NODE_2: [
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
        ],
        ISSBox.N2_EU_CORRIDOR: [
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
        ],
        ISSBox.N2_US_CORRIDOR: [
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
        ],
        ISSBox.EU_LAB: [
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.EU_LAB,
        ],
        ISSBox.US_LAB: [
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
        ],
        ISSBox.US_N1_CORRIDOR: [
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
        ],
        ISSBox.NODE_1: [
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
        ],
        ISSBox.N1_N3_CORRIDOR: [
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
        ],
        ISSBox.NODE_3_A: [ISSBox.NODE_3_B, ISSBox.NODE_3_A],
        ISSBox.NODE_3_B: [ISSBox.NODE_3_B],
        ISSBox.N3_CUPOLA_CORRIDOR: [ISSBox.NODE_3_B, ISSBox.N3_CUPOLA_CORRIDOR],
        ISSBox.CUPOLA: [ISSBox.NODE_3_B, ISSBox.N3_CUPOLA_CORRIDOR, ISSBox.CUPOLA],
    },
    ISSBox.N3_CUPOLA_CORRIDOR: {
        ISSBox.JPM: [
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.JPM,
        ],
        ISSBox.JPM_N2_CORRIDOR: [
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
        ],
        ISSBox.NODE_2: [
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
        ],
        ISSBox.N2_EU_CORRIDOR: [
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
        ],
        ISSBox.N2_US_CORRIDOR: [
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
        ],
        ISSBox.EU_LAB: [
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.EU_LAB,
        ],
        ISSBox.US_LAB: [
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
        ],
        ISSBox.US_N1_CORRIDOR: [
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
        ],
        ISSBox.NODE_1: [
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
        ],
        ISSBox.N1_N3_CORRIDOR: [
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
        ],
        ISSBox.NODE_3_A: [ISSBox.N3_CUPOLA_CORRIDOR, ISSBox.NODE_3_B, ISSBox.NODE_3_A],
        ISSBox.NODE_3_B: [ISSBox.N3_CUPOLA_CORRIDOR, ISSBox.NODE_3_B],
        ISSBox.N3_CUPOLA_CORRIDOR: [ISSBox.N3_CUPOLA_CORRIDOR],
        ISSBox.CUPOLA: [ISSBox.N3_CUPOLA_CORRIDOR, ISSBox.CUPOLA],
    },
    ISSBox.CUPOLA: {
        ISSBox.JPM: [
            ISSBox.CUPOLA,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
            ISSBox.JPM,
        ],
        ISSBox.JPM_N2_CORRIDOR: [
            ISSBox.CUPOLA,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.JPM_N2_CORRIDOR,
        ],
        ISSBox.NODE_2: [
            ISSBox.CUPOLA,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
        ],
        ISSBox.N2_EU_CORRIDOR: [
            ISSBox.CUPOLA,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
        ],
        ISSBox.N2_US_CORRIDOR: [
            ISSBox.CUPOLA,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
        ],
        ISSBox.EU_LAB: [
            ISSBox.CUPOLA,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
            ISSBox.N2_US_CORRIDOR,
            ISSBox.NODE_2,
            ISSBox.N2_EU_CORRIDOR,
            ISSBox.EU_LAB,
        ],
        ISSBox.US_LAB: [
            ISSBox.CUPOLA,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
            ISSBox.US_LAB,
        ],
        ISSBox.US_N1_CORRIDOR: [
            ISSBox.CUPOLA,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
            ISSBox.US_N1_CORRIDOR,
        ],
        ISSBox.NODE_1: [
            ISSBox.CUPOLA,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
            ISSBox.NODE_1,
        ],
        ISSBox.N1_N3_CORRIDOR: [
            ISSBox.CUPOLA,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
            ISSBox.N1_N3_CORRIDOR,
        ],
        ISSBox.NODE_3_A: [
            ISSBox.CUPOLA,
            ISSBox.N3_CUPOLA_CORRIDOR,
            ISSBox.NODE_3_B,
            ISSBox.NODE_3_A,
        ],
        ISSBox.NODE_3_B: [ISSBox.CUPOLA, ISSBox.N3_CUPOLA_CORRIDOR, ISSBox.NODE_3_B],
        ISSBox.N3_CUPOLA_CORRIDOR: [ISSBox.CUPOLA, ISSBox.N3_CUPOLA_CORRIDOR],
        ISSBox.CUPOLA: [ISSBox.CUPOLA],
    },
}

if __name__ == "__main__":
    create_path_lookup_table()
