name: build-documentation

on: 
  # Allow us to manually build the documentation when desired
  workflow_dispatch:
  # Schedule the documentation to automatically build weekly if we forget to update it
  schedule:
    - cron: '32 13 * * 1' # Mondays at 9:32 AM Eastern (13:32 UTC) (launch time for Apollo 11 :D)

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install all dependencies (including pdoc)
      - run: |
          pip install numpy
          pip install wheel
          pip install pybullet
          pip install -e .
      # Build documentation
      # NOTE: we'll wrap this run with XVFB because without it we get an error from an import
      # since there is no x server connection
      - name: setup-xvfb # Fake display for headless build
        uses: coactions/setup-xvfb@v1.0.1
        with:
          run: pdoc pyastrobee -o docs/pdoc/ -d google

      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs/pdoc/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
